// Generated by https://quicktype.io

export interface Usuario {
  id:           string;
  usuario:      string;
  email:        string;
  contrasena:   string;
  direccion:    string;
  esAgricultor: boolean;
  cuentaBanco:  string;
}
